FEAT: Editting color palette and add AdminButton UI.
social-food/social-food-ui pull request #3
Opened 2024-05-29 10:20 UTC by gumake999

1. 컬러 팔레트 값 수정
2. 어드민버튼 추가

2024-05-30 15:04 UTC, shinYeongHyeon requested changes

2024-05-30 15:04 UTC, shinYeongHyeon commented on src/packages/Button/AdminButton.tsx
> +    readonly color?: string;
@gumake999 단순 `string` 으로 받지 않고, type 혹은 enum으로 만들어서 받는건 어떨까 ?

가령 쓰는 곳에서
```
<Button color={SUI_COLORS.RED.RED01} 
```

이런식으로 쓸 수 있도록,
이렇게 하려면 이제 SUI_COLORS 와 같은 Type 혹은 ENUM 정의도 해야하지만, 단순 string을 넘겨받아서 생길수있는 오류를 방지할수도 있고, 가독성 및 사용성도 훨씬 좋아질것같아

2024-05-31 06:17 UTC, gumake999 commented on src/packages/Button/AdminButton.tsx
> +    readonly color?: string;
@shinYeongHyeon 
컬러를 colors 정의된 값 중에서 받도록 수정해보았습니당 
[추가]
- disabled false일 때 cursor: pointer로 변경
- 주입 받은 색(colors 내 정의된 색)을 backgroundColor로 사용하도록 변경

2024-06-02 09:41 UTC, shinYeongHyeon requested changes
@gumake999 이부분은 배포할수있도록 package.json 에 patch 버전 하나 올려주세요!

2024-06-02 13:00 UTC, gumake999 commented
> @gumake999 이부분은 배포할수있도록 package.json 에 patch 버전 하나 올려주세요!

patch 버전을 21로 변경합니다.

2024-06-02 14:36 UTC, merged