FEAT: Add-admin-typography-component
social-food/social-food-ui pull request #4
Opened 2024-06-09 13:41 UTC by gumake999

admin typography 추가
- 사용할 폰트 파일 추가

2024-06-10 04:50 UTC, shinYeongHyeon requested changes

2024-06-10 04:50 UTC, shinYeongHyeon commented on package.json
> +  "version": "0.0.22",
@gumake999 이거는 승인한후에, 머지 직전에 올리고 하는거로 할게요

2024-06-10 04:50 UTC, shinYeongHyeon commented on src/packages/Typography/useAdminTypography.tsx
> +
해당 파일에 함수들이 전체적으로, 의도하지 않은 값이 들어왔을때 처리가 부족한 듯 해요

2024-06-10 05:05 UTC, gumake999 commented on src/packages/Typography/useAdminTypography.tsx
> +
1. TypographyType 으로 타입을 강제하지만, 만약 타입스크립트 등을 쓰지 않을 때의 대비가 필요
2. 커스텀 값을 받을 수 있는 항목들에 이상한 string값 대비 필요

2024-06-13 10:44 UTC, gumake999 commented
[수정사항]
1. 입력 값 검증 및 기본값 강제하는 구문 추가
2. 기타 수정
 - 텍스트 내용을 children 으로 받도록 수정
 - size, weight 의 정상 값 정의를 위한 palette 추가
 - font-family를 기본 css에서 정의하던 것을 텍스트 스타일 쪽으로 이동
 - 600 semi-bold 파일 추가

2024-06-16 12:25 UTC, shinYeongHyeon requested changes

2024-06-16 12:25 UTC, shinYeongHyeon commented on src/packages/Palettes/sizes.palette.ts
> +    if (isString)
if 문구 안의 내용이 한줄이어도 `{}` 는 썼으면 좋겠습니다

2024-06-16 12:25 UTC, shinYeongHyeon commented on src/packages/Palettes/sizes.palette.ts
> +    fontSize.push(pushItem);
위의 내용과 반대되긴하지만, 해당 for문을 한줄로 일수있을 것 같습니당

2024-06-17 13:54 UTC, gumake999 commented on src/packages/Palettes/sizes.palette.ts
> +    fontSize.push(pushItem);
@shinYeongHyeon 😱 우옷 for 문 간단하게 줄여봤습니다

2024-06-17 13:56 UTC, gumake999 commented
[수정사항]
- rangeFontSizes 함수 내 for문 내부를 간략하게 수정 및 마지막 인자 isString이 아닌 isPixel로 변경

2024-06-18 07:49 UTC, shinYeongHyeon approved these changes

2024-06-18 07:53 UTC, merged