FEAT: Add basic typography component
social-food/social-food-ui pull request #8
Opened 2024-07-12 08:49 UTC by gumake999

- 기본적으로 사용할 타이포 컴포넌트 추가

2024-07-14 14:49 UTC, shinYeongHyeon requested changes

2024-07-14 14:49 UTC, shinYeongHyeon commented on src/packages/Palettes/weights.palette.ts
추후에는 Admin 과 그냥 User (이후부터 유저라 명칭할게요) 을 분리하는것도 좋을듯

2024-07-14 14:49 UTC, shinYeongHyeon commented on src/packages/Typography/User/Typography.tsx
> +    <Component
q) 이 `Component` 와 `as` 면 `<h1>제목입니당</h1>` 와 같이 SEO 에서 동일하게 인식하나요 ?

2024-07-15 08:23 UTC, gumake999 commented on src/packages/Typography/User/Typography.tsx
> +    <Component
@shinYeongHyeon  as 값이 있으면 그 값의 태그로 생성됩니다! (없으면 기본적으로 설정해둔 <p>로 생성)

2024-07-23 12:43 UTC, merged